# Generated by Django 5.0.6 on 2025-07-03 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoExtrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('cpf_usuario', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('usar_c6', models.BooleanField(default=False, verbose_name='C6 Bank')),
                ('usar_bradesco', models.BooleanField(default=False, verbose_name='Bradesco')),
                ('usar_bb', models.BooleanField(default=False, verbose_name='Banco do Brasil')),
                ('usar_bb_cartao', models.BooleanField(default=False, verbose_name='BB Cartão')),
                ('usar_itau', models.BooleanField(default=False, verbose_name='Itaú')),
                ('arquivo_c6', models.FileField(blank=True, null=True, upload_to='extratos/')),
                ('arquivo_bradesco', models.FileField(blank=True, null=True, upload_to='extratos/')),
                ('arquivo_config', models.FileField(blank=True, null=True, upload_to='configs/', verbose_name='Arquivo de Configuração (opcional)')),
                ('saldo_inicial_c6', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Saldo inicial C6')),
                ('saldo_inicial_bradesco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Saldo inicial Bradesco')),
                ('saldo_inicial_bb', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Saldo inicial BB')),
                ('saldo_inicial_itau', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Saldo inicial Itaú')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
                ('arquivo_resultado', models.FileField(blank=True, null=True, upload_to='resultados/')),
                ('sankey_data', models.TextField(blank=True, null=True, verbose_name='Dados dos Gráficos Sankey')),
            ],
            options={
                'verbose_name': 'Processamento de Extrato',
                'verbose_name_plural': 'Processamentos de Extratos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('bb', 'Banco do Brasil'), ('bb_cartao', 'BB Cartão'), ('itau', 'Itaú')], max_length=20)),
                ('arquivo', models.FileField(upload_to='extratos/')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='extratos_app.processamentoextrato')),
            ],
            options={
                'verbose_name': 'Arquivo de Extrato',
                'verbose_name_plural': 'Arquivos de Extratos',
                'ordering': ['banco', 'ordem'],
            },
        ),
    ]
