# Generated by Django 5.0.6 on 2025-08-31 19:59

import extratos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extratos_app', '0002_security_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentoextrato',
            name='arquivo_c6_cartao',
            field=models.FileField(blank=True, null=True, upload_to=extratos_app.models.upload_to_secure_path),
        ),
        migrations.AddField(
            model_name='processamentoextrato',
            name='usar_c6_cartao',
            field=models.BooleanField(default=False, verbose_name='C6 Cartão'),
        ),
    ]
